[project]
name = "ai-btc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dash>=3.2.0",
    "dotenv>=0.9.9",
    "pandas>=2.3.3",
]
